### ISSUE TITLE
Crash after `lsp-workspace-restart`

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/emacs#1]
After running `lsp-workspace-restart` it seem emacs crash and I only can get those logs

![2022-11-11_09-44](https://user-images.githubusercontent.com/7820865/201344317-81ff6c2e-9a9d-457a-9d8c-324eb672efd4.png)

INFO:
Compiled emacs-lsp/emacs with --with-native-compilation flag on debian 11

**Comment by sebastiansturm** [comment]
I have also seen a few segfaults on Emacs 29 (with native compilation, on Ubuntu 22.04, with the native json-rpc patches applied). For me it always happened when trying to open files (or at least that's what I remember I've been doing at about that time). Unfortunately I don't have a backtrace; have been running it under gdb all day at work, and had it randomly open a few hundred or thousand files yesterday but no luck so far...

**Comment by yyoncho** [comment]
There is one issue that I am aware of. The close can be called and there might be pending write in the other thread. I have a solution for it (with the help of @606u), but I have to find the time to integrate it.

**Comment by yyoncho** [comment]
I pushed a patch provided by @606u . It is still not we are going to have in the end, but it will most likely improve/solve that issue.

**Comment by ericdallo** [comment]
I confirmed this is working with latest commit, thank you!
