### ISSUE TITLE
Slow indexing of rust-analyzer on Apple Silicon

### ISSUE THREAD

**Issue by gagbo** [emacs-lsp/emacs#3]
Hi,

Still the same issue as pointed out on Discord:

Using:
- a M1 MBP,
- with Doom Emacs (emacs-lsp/lsp-mode@e870ce21d33ce84e1e7e29d72ed7e7451ea11dae)
- with current head here (emacs-lsp/emacs@f34bbbdc8561f5e361d7404c20280cb454051933),

when I open a rust project Rust-Analyzer starts, but it doesn't take all the resources at all, leading to a VERY (probably by a factor 10) slow initialization of the cache. See this screenshot of btop resource usage:
![Capture d’écran 2022-11-14 à 08 59 36](https://user-images.githubusercontent.com/10496163/201609063-5c4fc621-9ec7-460b-ad84-5ad575bbe776.png)

Opening the same project with vim spawns more threads on demand (peaks to 30 for this project) and uses all available CPU time (peaks to 100% _all_ cores), leading to way faster indexing. I could not repro this on Linux, but I didn't try with this commit yet.

**Comment by gagbo** [comment]
(And emacs 28 upstream acts like vim, so there's a hidden regression somewhere in the fork :( )

**Comment by ericdallo** [comment]
Maybe related to https://github.com/emacs-lsp/emacs/issues/5 ?

**Comment by gagbo** [comment]
I think the issue is fixed after a rebase to emacs-29 (I'm testing https://github.com/gagbo/emacs/tree/json-rpc-29 which I'll rebase probably once a week or a fortnight). I have peak CPU usage, and the status in the modeline reported up to 8 compilation tasks in parallel when going into a Rust buffer, which is what I expected.

![Capture d’écran 2022-12-08 à 10 02 44](https://user-images.githubusercontent.com/10496163/206404230-9f0931f8-1c16-402b-afba-730ed10d9757.png)

Therefore I'm closing the issue.
- A separate thread for lsp messaging is a "new feature".
- There's no way a  "new feature" makes it to a stable branch as emacs-28
- Therefore, having the issue only with the patch on top of emacs-28 is irrelevant.
