### ISSUE TITLE
Rebase on top of `emacs-29`

### ISSUE THREAD

**Issue by gagbo** [emacs-lsp/emacs#6]
`emacs-29` branch has been cut last week.

The issue serves as a reminder that the current `json-rpc` branch is built on top of `emacs-28`, to track rebase on `emacs-29`, and to remind myself to try to rebase at some point when I have time

**Comment by mattiasdrp** [comment]
The rebase is actually pretty straighforward, you'll just have to fix the conflict in .clang-format (I just did it here: https://github.com/mattiasdrp/emacs)

**Comment by gagbo** [comment]
Oh yeah I was going to make a PR but it turns out it's another branch to create

**Comment by indigoviolet** [comment]
@yyoncho et al, please consider having the emacs-29-json-rpc branch so that PRs can be contributed back and incompatibilities noted.

**Comment by gagbo** [comment]
FOSS work is volunteer work; it takes time and I don't think that 29 was ever out of consideration. We just have to wait for the next occasion they have time to look into it and answer the various issues

**Comment by yyoncho** [comment]
Pushed this and tested it for a while: https://github.com/emacs-lsp/emacs/tree/json-rpc-29 . If it turns out to be fine I will force push in json-rpc branch. It seems to me that it will make sense to have 2 versions.

1. Rebased on the latest release
2. Rebased on master

**Comment by mattiasdrp** [comment]
That's nice! I dropped my branch and am using yours. I currently have severe freezing with clojure-lsp with this branch (like I had with mine) that I don't have with the original 29 branch. I'll do some profiling to see what's happening, it looks like it's caused by the format buffer on save but I'm not sure

**Comment by yyoncho** [comment]
@mattiasdrp I guess that can happen if the sync methods fail to go to the UI thread. That part will be rewritten and it will work reliably (It won't depend on being able to get the global lock and then using timers).

**Comment by gagbo** [comment]
> Pushed this and tested it for a while: https://github.com/emacs-lsp/emacs/tree/json-rpc-29 . If it turns out to be fine I will force push in json-rpc branch. It seems to me that it will make sense to have 2 versions.

Just going to close this then.

>     1. Rebased on the latest release
> 
>     2. Rebased on master

Good to know!
